version: "3.9"

services:
  java-lightweight:
    build: .
    container_name: java-lightweight
    ports:
      - "2000:2000"
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "256m"
